baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Irvine Municipal Utilities"

[params]
    Id = "imuwater"
    Facebook = "https://www.facebook.com/cdpky"
    BillPay = "https://portal.utilitydistrict.com/2588"

[blackfriday]
    extensions = ["hardLineBreak"]

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
